### ISSUE TITLE
can't load out the newest tank

### ISSUE THREAD

**Issue by QinSparrow** [mikeoverbay/TankExporter#53]
Hello, your fruitful work is worthy of respect and admiration. Now I have some problems, which is probably starting with The World of Tanks version 1.15.0.0, when I can already see the AMBT and WZ114 files in the res/package, and since then the WT12 model has come out, but I have not been able to see these new tanks from the tank exporter for two months. In addition, the French, Chinese and Czech tanks of tier 8 cannot be displayed, the model of the lion tank cannot be exported, and some Czech tanks of tier 6 and tier 7 cannot be exported else. Please pay attention to these problems in your spare time and sincerely hope that you can fix them one day. Not hastening , just some feedback in use as a user of your program. Thank you very much for your powerful software.

**Comment by mikeoverbay** [comment]
It is easy my friend..
Go to File / Settings and click on Clear Temp Folder.
A window will pop up. Click yes to flush the data. This will make tank export rebuild the data for what tanks are in the game.
Let me know if this works for you.
Thanks for the info.

**Comment by QinSparrow** [comment]
great! your words does work! now AMBT、WZ114 and so on come out. but there still maintain a problem that everytime i start the tank exporter, a window will pop up to notice me that a png in crash file of G119 Pz.58FL lost, and the french、chinese、czech tank of tier 8 can't appear on the tier tree. thanks a lot for your help.

**Comment by mikeoverbay** [comment]
You're welcome!
Can you take a screen shot of that popup and the tier 8 tree?

**Comment by QinSparrow** [comment]
![Crashed! 2022_2_28 22_26_32](https://user-images.githubusercontent.com/89339766/156001213-784f9fdb-ab7d-45cc-b97b-e92b1e1c4ba1.png)
![ Tank Exporter Version_ 1 0 0 121 2022_2_28 22_26_56](https://user-images.githubusercontent.com/89339766/156001217-8155cd18-cbdb-46de-9df0-a75f3d9a5774.png)
hello! these are the things out of the way. maybe you can solve this matter. gratefully .

**Comment by mikeoverbay** [comment]
This is very strange.
Can you see if the .png is in gui-part1.pkg or gui-part2.pkg? 
The path is in that first crash image. 
Very strange.

**Comment by QinSparrow** [comment]
here i'm back to export thing to u. following the path , i find that in gui-part2.pkg/gui/map/icon/vehicle, there only exist the germany-G119_Panzer58_BF.png and germany-G119_Panzer58.png but germany-G119_Panzer58_FL.png. and in gui-part2.pkg/gui/map/shop/vehicle, only in the file"600X450" exist the png of the three twinstank. similar problem also happen in the  gui-part1.pkg. swear to god i've never open these two pkg or use things inside before. quite a strange problem.

**Comment by mikeoverbay** [comment]
This is what a search in PKG Explorer returned :
gui/maps/icons/vehicle/contour/germany-G119_Panzer58_FL.png
gui/maps/icons/vehicle/germany-G119_Panzer58_FL.png
gui/maps/icons/vehicle/small/germany-G119_Panzer58_FL.png
gui/maps/shop/vehicles/180x135/G119_Panzer58_FL.png
gui/maps/shop/vehicles/360x270/G119_Panzer58_FL.png
gui/maps/shop/vehicles/600x450/G119_Panzer58_FL.png
=================================
In PKG files:
gui-part1.pkg
gui-part2.pkg

You can use * in a tag to find all occurrences (G119_Panzer58_FL.png*) in PGK Explorer.
I am at a loss my friend.. Sorry :(

**Comment by QinSparrow** [comment]
thanks a lot for your help. now there maintains some problems that i can see some skin part in "load this", for instance, concept 1B's  hull(skin) and obj 140's turret(skin).some tanks have not one set of skin, and for instance, for A skin, i can find gun(skin),turret(skin),hull(skin),chassis(skin) all via "load this" but for B skin i can not view all the four parts
![Components 2022_3_8 14_24_18](https://user-images.githubusercontent.com/89339766/157179241-4aa7ff4b-e8d6-47c0-b124-05b43b10045b.png)
a picture of concept 1B's "load this".

**Comment by QinSparrow** [comment]
yes.every set of skin should be 4 parts: chassis ,turret , gun , hull

**Comment by mikeoverbay** [comment]
I'm looking in to this. I seem to be missing some parts of the _skin tanks too

**Comment by mikeoverbay** [comment]
I pushed an update.
It should work a lot better finding the _skin tanks. I re-wrote the section of code.
However, I can not find the 3rd _skin data for the russian 140. I looked in all the packages. It is a mystery!

**Comment by QinSparrow** [comment]
To prevent problems with my tank exporter due to my exploitation of the game's files, I deleted the game today and re-downloaded the HD version of the client. However, the problem remains unresolved, including opening the exporter to indicate that the part is missing PNG and part of some SKIN is still missing. OMG , GG. and i have re-downloaded your no.122 version today. nothing worked. whatever, Thank you for your long-term enthusiastic help.

**Comment by Orcberto** [comment]
My 2 cents for this conversation: when viewing the S31_Strv_K model, the Tank Exporter version 1.0.0.123 was not able to find the hull part of the tank's skin version (Sabaton version). Searching manualy I found the hull part in the particles.pkg package... It is for the version 1.16.1.0 of the Wot steam version. I hope you find the information useful. Thanks for this wonderfull program.

**Comment by mikeoverbay** [comment]
Interesting Orcberto... I'll have a look.
QinSparrow, There is a log file written in to the temp folder. Maybe it has something there? File name is : wot_tempStartup_log.txt
